spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/auction-realm/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gateway server"
    description: "MyBank gateway server"
    version: "1.0.0"

logging:
  level:
    # Set default level higher (e.g., INFO) to avoid too much noise
    root: INFO
    # Enable DEBUG for specific components related to Gateway, WebSockets, Security, Netty
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
    io.netty: INFO # Optional: Netty can be very verbose, start with INFO
    com.example.gatewayserver: DEBUG # Your gateway's base package (for custom filters etc.)
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 2