package com.example.payments.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RefundSucceededEventDto {
    private UUID eventId; // New event ID generated by PaymentsService
    private LocalDateTime eventTimestamp;
    private UUID orderId; // Original order ID
    private String buyerId; // The ID of the user who made the payment
    private String paymentIntentId; // Original Stripe PaymentIntent ID
    private String refundId; // Stripe's refund ID
    private Long amountRefunded; // Amount refunded,
    private String currency;
    private String status; // e.g., "succeeded" from Stripe refund object
    private LocalDateTime refundedAt; // Timestamp when the refund was processed
}
